name: "GO DAIKIN (Fixed)"
slug: godaikin-fixed
version: "1.0.12"
description: "Manage air conditioners through GO DAIKIN (with energy fix)"
startup: application
init: false
services:
  - "mqtt:need"
arch:
  - aarch64
  - amd64
hassio_api: true
homeassistant_api: true
options:
  godaikin_username: your@email.com
  godaikin_password: ""
  refresh_interval: 10
schema:
  godaikin_username: str
  godaikin_password: password
  refresh_interval: int
